### ISSUE TITLE
Escape Double Quotes in Literal

### ISSUE THREAD

**Issue by jchavez443** [neo4j/cypher-builder#345]
String literal values are not being escaped during the getCypher() for literal values.

```ts
// ...
const equality = Cypher.eq(nFooProp, new Cypher.Literal('"bar"') )
```

Is:
```cypher
MATCH(n)
WHERE n.foo = ""bar""
RETURN n limit 1
```

Should Be:
```cypher
MATCH(n)
WHERE n.foo = "\"bar\""
RETURN n limit 1
```

**Comment by angrykoala** [comment]
Hi @jchavez443 

Thanks for your report
This is a known issue (#241), however it is a breaking change, and thus it will be fixed in the next major release (2.0)

In the meantime, I recommend you use either `Cypher.Param` instead of literals, as it is the recommended approach for user input and will work on the current version as well as the next major version.

I'll close this now, as this issue will be tracked by #241
